# Generated by Django 4.2.16 on 2024-09-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pitch',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='pitch',
            name='composer',
        ),
        migrations.RemoveField(
            model_name='pitch',
            name='file',
        ),
        migrations.AddField(
            model_name='pitch',
            name='agency_email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pitch',
            name='composer_email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pitch',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
