# Generated by Django 4.2.16 on 2024-09-22 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pitches', '0002_remove_pitch_agency_remove_pitch_composer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='agency',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pitches_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pitch',
            name='composer',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pitches_sent', to=settings.AUTH_USER_MODEL),
        ),
    ]
