# Generated by Django 4.2.16 on 2024-09-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0004_remove_pitch_agency_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='agency_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pitch',
            name='composer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
