# Generated by Django 4.2.16 on 2024-09-22 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('agency', 'Agency'), ('composer', 'Composer')], max_length=10),
        ),
    ]
